spring.application.name=sensor-ingestion-service
server.port=8087
# Application Kafka
#spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.streams.application-id=mqtt-sensor-stream
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.topic=mqtttopic

# Application MQTT
#value.mqtt.url:tcp://localhost:1883
value.mqtt.clientid=testClient
value.mqtt.topic=topicTest


spring.datasource.url=jdbc:sqlserver://monitoring-iot-sql.database.windows.net:1433;database=database-monitoring
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect