name: Compilacion Servicio Ingesta
on:
  push:
    branches: [ "feature/feat-azure" ]

jobs:
  compilar-y-auditar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el codigo fuente
        uses: actions/checkout@v4

      - name: Iniciar Sesion en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Iniciar sesion en ACR
        run: az acr login --name datalyzeiotacr

      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: datalyzeiotacr.azurecr.io/samples/ingest-service:${{github.sha}}

      - name: Desplegar en Azure Container Apps
        run: |
          az containerapp update \
          --name ingest-service \
          --resource-group rg-monitoring-iot \
          --image datalyzeiotacr.azurecr.io/samples/ingest-service:${{github.sha}}
